const hikayeler = {
  "istanbul-avrupa": {
    "baslik": "Sihirli Boğazın Avrupa Yakası",
    "hikaye": "Bir varmış bir yokmuş, iki kıtayı birbirine bağlayan, denizinden gümüş rengi balıkların atladığı masalsı bir şehir varmış. Bu şehrin Avrupa Yakası'nda, bulutlara doğru uzanan ve yüzyıllardır şehri şefkatle izleyen taş bir nöbetçi dururmuş; adına Galata Kulesi derlermiş. Kule, her sabah güneşin ilk ışıklarıyla uykusundan uyanır, Boğaziçi'nin serin sularında yıkanan martılara neşeyle selam verirmiş. Hemen ilerisinde, taş döşeli uzun bir caddede çanını 'çın çın' çalarak süzülen kırmızı bir tramvay varmış. Bu tramvay, her gün okula ve oyuna koşturan çocukları alır, onlara şehrin en güzel sırlarını anlatırmış.\n\nKış aylarında, tarihi yarımadanın etrafını ince bir sis perdesi kapladığında, sokak köşelerinden yükselen kavrulmuş kestane ve taze simit kokusu birbirine karışır, dar sokaklarda seksek oynayan çocukların içini ısıtırmış. Mısır Çarşısı'ndan yayılan rengarenk baharat kokuları rüzgara karışır, eski surların taşları arasında gizlenen kedi yavrularına ninni gibi gelirmiş. Vapurlar, arkalarında bembeyaz köpükler bırakarak koyu mavi denizin üzerinde süzülürken, Boğaz'ın neşeli yunusları onlara yarışarak eşlik edermiş.\n\nAkşamları gökyüzü yavaşça mora boyandığında, Avrupa Yakası'nın ışıkları birer ateş böceği gibi yanmaya başlar ve tüm tepeyi aydınlatırmış. Karşı kıyıya, masmavi sulara vuran bu yansımalar, şehre altın bir kolye gibi dizilirmiş. Efsaneye göre yer altındaki devasa sarnıçlarda uyuyan masal perileri, sadece iyi kalpli çocukların duyabileceği bir sesle şu sırrı fısıldarmış: 'Bu şehirde her dar sokak, eninde sonunda sonsuz bir denize ve tükenmez bir umuda çıkar.'",
    "gorsel": "assets/istanbul-avrupa.jpg"      
  },
  "ankara": {
    "baslik": "Bozkırın Altın Kalbi",
    "hikaye": "Bir zamanlar, Anadolu'nun uçsuz bucaksız sarı bozkırlarının tam ortasında, rüzgarı sert ama insanlarının kalbi sımsıcak olan bir şehir varmış. Bu şehrin adı Ankara'ymış. Şehrin kalbinde, bembeyaz kuğuların zarafetle yüzdüğü yemyeşil bir park ve en yüksek tepesinde gökyüzüne dokunan asırlık bir taş kale bulunurmuş. Dar ve yokuşlu sokaklarında saklambaç oynayan çocuklar, sabahları fırınlardan yükselen taze çıtır simitlerin kokusuyla uyanırmış.\n\nKış geldiğinde, şehrin meşhur ayazı sokakları dolaşır, ama lapa lapa yağan kar Ankara'yı bembeyaz, pamuktan bir yorgan gibi örtermiş. Çocuklar renkli yün atkılarına sıkıca sarılır, dik yokuşlardan kızaklarıyla neşe içinde kayarlarmış. İlkbahar yüzünü gösterdiğinde ise bozkır uykusundan uyanır; vadilerde açan sarı çiğdemler ve pembe badem çiçekleri şehre mis gibi bir umut kokusu yayarmış. Uzak dağlardan inen serin rüzgarlar, ağaçların yaprakları arasında gizli masallar fısıldarmış.\n\nGeceleri, şehrin ulu tepesindeki Anıtkabir'in asil ışıkları, Ankara'nın her köşesinden altın bir yıldız gibi parlarmış. Efsaneye göre, bu topraklarda yaşayan eski bilgeler ve kahramanlar, gökyüzündeki en parlak yıldızları Ankaralı çocuklara daima doğru yolu göstersin diye bırakmış. Rüzgar her estiğinde, kalenin yüksek surlarından tüm şehre şu sihirli mesaj yayılırmış: 'Bozkırın ortasında açan en güzel çiçek, kalplerde her sabah yeniden yeşeren cesaret ve sevgidir.'",
    "gorsel": "assets/ankara.jpg"
  },
  "istanbul-asya": {
    "baslik": "Kız Kulesi'nin Masal Yakası",
    "hikaye": "Bir varmış bir yokmuş, masmavi denizlerin ortasında, dalgaların nazlı nazlı kıyıya vurduğu huzur dolu bir yaka varmış. İstanbul'un Asya Yakası denilen bu zümrüt yeşili diyarda, denizin tam ortasında zarif bir prenses gibi süzülen Kız Kulesi yaşarmış. Martılar en güzel şarkılarını bu kuleye söyler, Haydarpaşa Garı'nın devasa taş merdivenlerinde ise uzak diyarlardan gelen masallar fısıldanırmış. Sahil boyunca uzanan asırlık çınar ağaçlarının gölgesinde, çocuklar neşeyle koşturur, bisikletlerinin zilleriyle rüzgara eşlik edermiş.\n\nİlkbahar geldiğinde, Çamlıca Tepesi rengarenk erguvanlar ve lalelerle bezenir, çocukların gökyüzüne saldığı uçurtmalar bulutlarla dans edermiş. Eski vapurlar iskeleye yanaştığında, yolcuların attığı çıtır simitleri havada kapan martıların sevinç çığlıkları her yeri sararmış. Yaz akşamlarında Moda sahiline vuran ılık rüzgar, dondurma yiyen çocukların yüzünü okşar, havaya karışan iyot ve çam kokusu herkesin içine tatlı bir huzur doldururmuş.\n\nGüneş batarken, karşı yakanın altın sarısı ışıkları Boğaz'ın yakamozlu sularına yansır ve Asya Yakası'nı sihirli bir pırıltı kaplarmış. Efsaneye göre, Kız Kulesi geceleri yıldızların altında uyanır ve denize bakarak dilek tutan çocuklara şu gizli mesajı fısıldarmış: 'Gerçek sihir, denizin mavisiyle gökyüzünün kucaklaştığı yerde, sevdiklerinle paylaştığın sıcacık bir gülümsemededir.'",
    "gorsel": "assets/istanbul-asya.jpg"
  },
  "izmir": {
    "baslik": "Ege'nin İmbat Kokulu İncisi",
    "hikaye": "Bir zamanlar, masmavi Ege Denizi'nin kıyısında, güneşin her sabah altın sarısı ışıklarıyla gülümsediği pırıl pırıl bir şehir varmış. Bu güzel şehrin adı İzmir'miş. Şehrin kalbinde, zarif taş oymalarıyla süslü ve yıllara meydan okuyan meşhur bir Saat Kulesi dururmuş. Meydanda uçuşan yüzlerce güvercin, saatin her çan vuruşunda gökyüzüne kanat çırparak denizin üzerindeki bulutlarla dans edermiş. Sahil boyunca uzanan boyu göğe eren palmiye ağaçları, rüzgar estikçe çocuklara fısıltıyla eski denizci masalları anlatırmış.\n\nSabahları sokaklardan fırından yeni çıkmış sıcacık boyoz kokuları yükselir, vapurlara binen telaşlı insanlar ellerindeki gevrekleri denizdeki neşeli martılarla paylaşırmış. Yaz günleri Kordon'un yemyeşil çimlerinde koşturan çocuklar, uçurtmalarını Ege'nin bulutsuz gökyüzüne salarken denizden esen 'İmbat' rüzgarı terlemiş yanaklarını serinletirmiş. Akşamüstü olunca, güneş körfezin sularına kırmızı ve turuncu renkler bırakarak yavaşça batar, balıkçı tekneleri yakamozların arasında sessizce süzülürmüş.\n\nGeceleri, körfezin her iki yakasındaki ışıklar denizin ayna gibi sularında parıldamaya başladığında, İzmir adeta yıldızlardan örülmüş bir kolyeye dönüşürmüş. Efsaneye göre, denizin derinliklerinde yaşayan iyilik perileri, dalgaların kıyıya vuran tatlı sesiyle uykuya dalan çocukların kulağına şu sırrı fısıldarmış: 'Hayat, tıpkı bu engin deniz gibi; sevinçle, umutla ve sıcacık dostluklarla paylaşıldığında güzeldir.'",
    "gorsel": "assets/izmir.jpg"
  },
  "nevsehir": {
    "baslik": "Peribacalarının Gizemli Masalı",
    "hikaye": "Bir varmış bir yokmuş, Anadolu'nun tam kalbinde, doğanın kendi elleriyle şekillendirdiği büyülü bir diyar varmış. 'Güzel Atlar Ülkesi' olarak bilinen bu eşsiz şehrin adı Nevşehir'miş. Rüzgar ve yağmurun binlerce yıl boyunca sabırla oyduğu, gökyüzüne doğru şapkalı devler gibi uzanan peribacaları, bu toprakların en kadim bekçileriymiş. Kapadokya'nın kıvrımlı vadilerinde, gizemli yeraltı şehirlerinin serin taş koridorlarında koşturan çocuklar, güneş battığında iyilik perilerinin bu taştan kulelerde uyandığına inanırmış.\n\nSabahın ilk ışıkları henüz ufukta belirmeden, vadilerin sessizliği gökyüzüne yavaşça yükselen rengarenk sıcak hava balonlarının alev sesleriyle bozulurmuş. Kırmızı, sarı, mavi balonlar devasa masal kuşları gibi havalanırken; aşağıda, vadinin altın sarısı tozlarını havalandırarak dört nala koşan özgür yılkı atları onlara neşeyle eşlik edermiş. İlkbahar rüzgarları estiğinde, kayalara oyulmuş güvercinliklerden havalanan taklacı güvercinler, gökyüzündeki balonlarla bulutların arasında saklambaç oynar, kızıl vadilerin yamaçlarında açan yabani çiçekler etrafa tarifsiz bir huzur yayarmış.\n\nGüneş ufkun ardında kaybolup da gökyüzü turuncudan laciverte döndüğünde, kayalara oyulmuş eski taş evlerin küçük pencerelerinden süzülen sarı ışıklar karanlığı şefkatle aydınlatırmış. Gökyüzündeki parlak yıldızlar peribacalarının hemen üzerine indiğinde, Nevşehir adeta uykudaki dev bir masal kitabına dönüşürmüş. Efsaneye göre, gece rüzgarı vadiler arasında süzülürken sadece hayal kurmayı unutmayan çocukların duyabileceği bir sesle şu sırrı fısıldarmış: 'Doğanın sabırla işlediği bu büyülü dünyada, en büyük mucizeler daima gökyüzüne umutla bakan kalplerde saklıdır.'",
    "gorsel": "assets/nevsehir.jpg"
  },
  "antalya": {
    "baslik": "Akdeniz'in Güneş Yürekli Şehri",
    "hikaye": "Bir zamanlar, masmavi Akdeniz'in ılık sularıyla kucaklaşan, sırtını göklere uzanan ulu Toros Dağları'na yaslamış sımsıcak bir şehir varmış. Bu güneş yürekli şehrin adı Antalya'ymış. Altın sarısı uçsuz bucaksız kumsallarında yalınayak koşturan çocuklar, dalgaların kıyıya taşıdığı sedefli deniz kabuklarını toplayıp gizli hazineler gibi saklarmış. Şehrin dört bir yanını saran yemyeşil portakal bahçeleri, ilkbahar geldiğinde bembeyaz çiçekler açar ve hafif bir meltem estikçe tüm sokaklara tatlı, huzur veren bir koku yayarmış.\n\nÖğle vakti güneş gökyüzünde pırıl pırıl parlarken, sarp kayalıklardan bembeyaz köpükler saçarak dökülen neşeli şelaleler, su perilerinin eski zamanlarda söylediği şarkıları mırıldanırmış. Binlerce yıllık devasa antik tiyatroların taş basamaklarında seksek oynayan çocuklar, esen rüzgarın taşıdığı kahramanlık efsanelerini dinler, yaz gecelerinde kumsallardan denize ulaşmaya çalışan minik caretta caretta kaplumbağalarına sevgiyle yol gösterirlermiş.\n\nAkşamüstü ufukta güneş yavaşça erirken, denizin yüzeyi binlerce altın damlasıyla parlamaya başlar ve gökyüzü pembeden mora doğru büyülü bir renge bürünürmüş. Kaleiçi'nin dar, taş döşeli sokaklarındaki cumbalı eski evlerin pencerelerinden sızan sıcak ışıklar, şehri aydınlatırken limandaki ahşap tekneler hafifçe sallanarak uykuya dalarmış. Efsaneye göre, Akdeniz'in derinliklerinden esen ılık rüzgar, dalga sesleri eşliğinde çocukların kulağına şu sırrı fısıldarmış: 'Dünyanın en parlak güneşi gökyüzünde değil, sevgiyi, neşeyi ve umudu paylaşan altın kalplerde doğar.'",
    "gorsel": "assets/antalya.jpg"
  },
  "mardin": {
    "baslik": "Taşların Şiir Yazdığı Masal Şehri",
    "hikaye": "Bir zamanlar, uçsuz bucaksız Mezopotamya ovasına yüksek bir tepeden altın bir taç gibi bakan, her sokağı tarih kokan büyülü bir şehir varmış. Bu şehrin adı Mardin'miş. Sarı kalker taşından yapılmış, hiçbiri diğerinin manzarasını kapatmayan zarif evleri, güneşi kucaklayan birer masal şatosu gibiymiş. 'Abbara' denilen kemerli serin geçitlerde neşeyle koşturan çocuklar, taş merdivenlerde seksek oynarken adeta zamanın içinde sımsıcak bir yolculuk yaparlarmış. Taş ustalarının nakış gibi işlediği duvarlar, kadim zamanların sırrını sessizce kalbinde taşırmış.\n\nGüneş en tepedeyken, gümüş telkari ustalarının çekiç sesleri ince bir melodi gibi dar sokaklara yayılır, havaya taze kavrulmuş badem şekeri ve mahlep kokusu karışırmış. Gökyüzünde süzülen ve sevinçle taklalar atan bembeyaz güvercinler, eski konakların teraslarından uçsuz bucaksız ovayı izleyen hayalperest çocuklara yoldaşlık edermiş. Göz alabildiğine uzanan Mezopotamya ovası, rüzgar estikçe altın rengi bir okyanus gibi dalgalanır, miniklere uzak diyarlardan geçen eski masal kervanlarının hikayelerini taşırmış.\n\nAkşam karanlığı çöktüğünde ise bu eşsiz şehir 'gündüz seyranlık, gece gerdanlık' efsanesini yaşamaya başlarmış. Tepedeki taş evlerin pencerelerinden süzülen ışıklar, gecenin karanlığında parlayan yıldızlarla birleşir ve Mardin, yeryüzüne serilmiş ışıltılı bir pırlanta kolyeye dönüşürmüş. Efsaneye göre, ovanın kalbinden esen ılık rüzgar, yıldızların altında uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en kalıcı ve en güzel saraylar taştan değil; sevgiyle, hoşgörüyle ve kardeşlikle inşa edilenlerdir.'",
    "gorsel": "assets/mardin.jpg"
  },
  "trabzon": {
    "baslik": "Karadeniz'in Zümrüt Yeşili Şehri",
    "hikaye": "Bir varmış bir yokmuş, hırçın dalgaların dövdüğü Karadeniz'in kıyısında, sarp dağların zümrüt yeşili ormanlarla kucaklaştığı masalsı bir şehir varmış. Bu şehrin adı Trabzon'muş. Bulutların zirvelerinden hiç eksik olmadığı bu yüksek dağlarda, sislerin arasına gizlenmiş ahşap yayla evleri pamuktan birer masal yuvasını andırırmış. Yaylaların serin çimenlerinde yalınayak koşturan yanakları al al olmuş çocuklar, yağmur damlalarıyla ıslanan fındık ağaçlarının arasında neşeyle saklambaç oynar, doğanın bu bitmek bilmeyen enerjisiyle şenlenirlermiş.\n\nGüneş yüzünü gösterip sisler dağıldığında, uçsuz bucaksız çay bahçelerinde neşeli türküler yankılanır, kemençenin o kıpır kıpır sesi vadiden vadiye seke seke dolaşırmış. Coşkuyla akan köpüklü derelerin kenarında el ele tutuşup horon vuran çocuklar, Karadeniz'in asi rüzgarlarıyla yarışırmış. Sarp kayalıklara bir kartal yuvası gibi tutunmuş efsanevi Sümela Manastırı, asırlardır ormanın gizli fısıltılarını dinler, dağların asırlık sırlarını gökyüzünde süzülen şahinlere anlatırmış.\n\nAkşam olup da gökyüzü yavaşça gri ve laciverte büründüğünde, ahşap evlerin kuzinelerinde yanan odunların çıtırtısı duyulur, havaya karışan sıcacık mısır ekmeği kokusu herkesin içini huzurla doldururmuş. Hırçın Karadeniz geceye doğru yavaşça durulur, kıyıya vuran beyaz köpüklü dalgalar uykuya dalan çocuklara tatlı bir ninni söylermiş. Efsaneye göre, ulu çam ağaçlarının arasından süzülen serin yayla rüzgarı, çocukların kulağına şu sırrı fısıldarmış: 'Gerçek güç ve cesaret, tıpkı bu hırçın dereler ve sarp dağlar gibi, zorluklar karşısında el ele verip asla pes etmeyen umut dolu kalplerdedir.'",
    "gorsel": "assets/trabzon.jpg"
  },
  "erzurum": {
    "baslik": "Palandöken'in Beyaz Masalı",
    "hikaye": "Bir zamanlar, bulutlara komşu olan yüksek mi yüksek dağların zirvesinde, yılın büyük bir kısmını bembeyaz bir battaniye altında uyuyarak geçiren görkemli bir şehir varmış. Bu şehrin adı Erzurum'muş. Gökyüzüne doğru gururla uzanan Çifte Minareli Medrese'nin mavi çinileri, güneş vurdukça buz kristalleri gibi parlarmış. Palandöken Dağı'nın eteklerinde yaşayan al yanaklı cesur çocuklar, lapa lapa yağan karın altında neşeyle koşturur, dondurucu ayaza rağmen içlerindeki sevinçle tüm sokakları ısıtırlarmış.\n\nKışın en sert günlerinde bile bu şehrin sokaklarından şen kahkahalar eksik olmazmış. Çocuklar tahta kızaklarına sıkıca tutunup dik yokuşlardan rüzgarla yarışırcasına kayarken, havada uçuşan kar taneleri onlara gümüş rengi bir yağmur gibi eşlik edermiş. Tarihi çarşıların taş kemerleri altında, sabırlı ustalar gece karası Oltu taşını birer mücevhere dönüştürürken, sobaların üzerinde neşeyle kaynayan çaydanlıklar üşüyen ellere sıcacık bir kucak açarmış. Kar ne kadar derin olursa olsun, bu şehrin insanlarının kapısı dostluğa ve misafire daima sonuna kadar açıkmış.\n\nGece olup da ayaz usulca şehri sardığında, gökyüzündeki yıldızlar adeta birer elmasa dönüşüp bembeyaz dağların zirvesinde pırıl pırıl parlamaya başlarmış. Kalın taş duvarlı eski evlerin pencerelerinden süzülen sarı ışıklar, uçsuz bucaksız beyazlığın ortasında umutla yanan ateş böceklerini andırırmış. Efsaneye göre, karlı zirvelerden kopup gelen deli rüzgar, soba başında masal dinleyerek uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en güçlü sıcaklık yanan ateşten değil; zorluklara birlikte göğüs geren, sevgi ve cesaret dolu yüreklerden gelir.'",
    "gorsel": "assets/erzurum.jpg"
  },
  "konya": {
    "baslik": "Sevgi Ovasının Turkuaz Sırrı",
    "hikaye": "Bir zamanlar, göz alabildiğine uzanan altın sarısı buğday tarlalarıyla çevrili, uçsuz bucaksız bir ovanın tam kalbinde, huzurla mayalanmış kadim bir şehir varmış. Bu barış dolu şehrin adı Konya'ymış. Şehrin tam ortasında yükselen Alaeddin Tepesi'nde koşturan neşeli çocuklar, ilkbaharın gelişiyle açan rengarenk lalelerin arasında saklambaç oynar, gökyüzüne saldıkları uçurtmalarla pamuk bulutlara selam gönderirlermiş. Şehrin merkezinde ise, gökyüzünün mavisini kıskandıracak kadar zarif olan turkuaz renkli Yeşil Türbe, güneşin ilk ışıklarıyla parıldayarak tüm ovaya şefkatli bir gülümseme dağıtırmış.\n\nGün ağardığında, asırlık çarşılardan ve eski taş sokaklardan usta ellerin nefes verdiği 'ney' adlı sihirli kamıştan süzülen o incecik, huzur dolu melodi yükselirmiş. Bu tatlı melodiyi duyan beyaz elbiseli bilgeler, tıpkı güneşin etrafında ahenkle dönen gezegenler gibi kollarını gökyüzüne açarak usulca dönmeye başlarmış. Onların bu sessiz ve büyüleyici dönüşü etrafa öyle bir sevgi dalgası yayarmış ki; ağaçlardaki kuşlar, kırlardaki kelebekler ve tarlalardaki minik canlılar bile bu iyilik dansına büyük bir neşeyle katılırmış. Şehrin çocukları, fırınlardan yayılan sıcacık etliekmek kokuları eşliğinde sokaklarda güvenle oynarken, tüm dünyanın kalbinde aslında aynı dostluk türküsünün çaldığını hissederlermiş.\n\nAkşam karanlığı yavaşça çöküp gökyüzü koyu bir laciverte büründüğünde, düz ve engin ovanın üzerinde beliren yıldızlar yere o kadar yakın görünürmüş ki, çocuklar pencereden ellerini uzatsa yıldızları toplayacaklarını sanırmış. Ovanın derinliklerinden kopup gelen ılık gece rüzgarı, asırlık türbenin etrafında usulca dolanıp şehre yayılırken, uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en büyük sihir, kim olursan ol kapını ve kalbini tüm canlılara ardına kadar açabilmektir; çünkü sevgi, her karanlığı aydınlatan tek ışıktır.'",
    "gorsel": "assets/konya.jpg"
  },
  "canakkale": {
    "baslik": "Boğazın Rüzgarlı ve Cesur Masalı",
    "hikaye": "Bir zamanlar, koyu mavi suların iki yeşil yakayı şefkatle kucakladığı, rüzgarın masallar anlatarak estiği cesur bir şehir varmış. Bu şehrin adı Çanakkale'ymış. Şehrin tam kalbinde, deniz kenarında kocaman, tahtadan yapılmış gizemli bir Truva Atı dururmuş. Sahilde neşeyle koşturan çocuklar, bu devasa atın gölgesinde saklambaç oynar, eski zaman kahramanlarının maceralarını hayal ederken Boğaz'dan köpükler saçarak geçen koca gemilere sevinçle el sallarlarmış.\n\nDört mevsim boyunca esen deli poyraz, efsanevi Kaz Dağları'nın mis gibi çam kokularını alır, Gelibolu'nun sessiz ve huzurlu tepelerine taşırmış. İlkbahar geldiğinde uçsuz bucaksız ayçiçeği tarlaları güneşe doğru sarı yüzlerini döner, kırlangıçlar masmavi gökyüzünde sevinçle dans edermiş. Tarihin en büyük destanlarının yazıldığı bu topraklarda, yemyeşil çimenlerin altında uyuyan kahramanlar rüzgarın tatlı ninnisiyle dinlenirmiş. Şehrin çocukları, barışın ve kardeşliğin ne kadar kıymetli olduğunu bu tepelerde uçurtma uçururken, rüzgarda salınan kırmızı gelincik çiçeklerinin fısıltısından öğrenirmiş.\n\nAkşam karanlığı çöküp de Boğaz'suları laciverte büründüğünde, vapurların yaktığı sarı ışıklar denizin üzerinde altın rengi yakamozlar oluştururmuş. Karşı yakada aralıksız yanıp sönen fenerler, karanlıkta yolunu arayanlara şefkatle göz kırparmış. Efsaneye göre, iki kıtayı birbirine bağlayan bu serin sulardan esen gece rüzgarı, dalga sesleri eşliğinde uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Gerçek kahramanlık savaşmakta değil; barışı, sevgiyi ve kardeşliği yeryüzünde sonsuza dek yaşatmaktadır.'",
    "gorsel": "assets/canakkale.jpg"
  },
  "sanliurfa": {
    "baslik": "Kadim Sırların ve Kutsal Suların Şehri",
    "hikaye": "Bir zamanlar, güneşin toprağı altın sarısına boyadığı, tarihin en eski masallarının doğduğu büyülü bir şehir varmış. Bu kadim şehrin adı Şanlıurfa'ymış. Şehrin kalbinde, aynayı andıran berrak sularında kutsal balıkların nazlı nazlı yüzdüğü gizemli Balıklıgöl bulunurmuş. Gölgeli avlularda ve külah biçimli kerpiç Harran evlerinin etrafında koşturan çocuklar, efsanelerle büyür, suyun içindeki sevimli sazan balıklarına neşeyle yem atarlarmış.\n\nGüneş en tepedeyken, binlerce yıllık Göbeklitepe'nin devasa taşları arasında dolaşan serin rüzgar, insanlığın ilk zamanlarından kalma ninnileri mırıldanırmış. Tarihi kapalı çarşıların taş kemerleri altından yükselen taze çekilmiş kahve ve fıstık kokuları, daracık sokakları doldurarak herkesin içini ısıtırmış. Yüksek kalenin burçlarından havalanan taklacı güvercinler, bereketli Harran Ovası'nın üzerinde süzülerek masmavi gökyüzüne barışın ve kardeşliğin resmini çizermiş.\n\nAkşam usulca çöküp de güneş kızıl bir tebessümle ufkun ardına saklandığında, Urfa'nın gökyüzü binlerce parlak yıldızla süslenirmiş. Balıklıgöl'ün etrafındaki asırlık ağaçların yaprakları arasından süzülen hafif rüzgar, suya yansıyan ay ışığıyla usulca dans edermiş. Efsaneye göre, bu toprakları koruyan iyilik perileri, gece yıldızların altında uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en büyük mucize; tıpkı ateşi serin bir suya dönüştüren o eski efsanedeki gibi, karanlığı aydınlığa, öfkeyi sevgiye ve şefkate dönüştürebilen iyilik dolu kalplerdir.'",
    "gorsel": "assets/sanliurfa.jpg"
  },
  "gaziantep": {
    "baslik": "Fıstık Yeşili Masal Şehri",
    "hikaye": "Bir zamanlar, bereketli toprakların güneşle kucaklaştığı, havasına her daim taze kavrulmuş fıstık ve tatlı bir baharat kokusunun karıştığı neşeli bir şehir varmış. Bu lezzet ve tarih dolu şehrin adı Gaziantep'miş. Şehrin tam ortasında heybetle yükselen kadim bir taş kale, eteklerindeki dar ve kıvrımlı sokaklara şefkatle gölge edermiş. Bu taş sokaklarda neşeyle koşturan çocuklar, sabahları fırınlardan yükselen sıcacık katmer kokusuyla uyanır, usta ellerin hamura masal gibi şekil verişini hayranlıkla izlerlermiş.\n\nGüneş tepeye tırmandığında, meşhur Bakırcılar Çarşısı'ndan yükselen o ritmik 'çın çın' çekiç sesleri, neşeli bir şarkı gibi tüm şehre yayılırmış. Ustaların bakıra sabırla işlediği çiçek motifleri, güneş vurdukça canlanıp çocuklara göz kırparmış. Şehrin saklı hazinesi Zeugma'da ise, binlerce minik ve renkli taşın bir araya gelerek oluşturduğu mozaikler, eski zamanların büyüleyici hikayelerini fısıldarmış. İlkbahar gelip de uçsuz bucaksız fıstık ağaçları yeşerdiğinde, ovalar adeta zümrüt rengi bir halıyla kaplanır, gökyüzünde süzülen kırlangıçlar bu bereketli topraklara sevinç şarkıları söylermiş.\n\nAkşam karanlığı çöküp de eski taş konakların pencerelerinden süzülen sarı ışıklar dar sokakları aydınlattığında, şehir tatlı bir huzura bürünürmüş. Avlulardaki şadırvanlardan usulca akan suyun sesi, yıldızların altında uykuya dalan çocuklara ninniler fısıldarmış. Efsaneye göre, bu bereketli ovaliden esen ılık gece rüzgarı, çocukların kulağına şu kadim sırrı fısıldarmış: 'Tıpkı binlerce farklı renkteki taşın bir araya gelip eşsiz bir mozaik yaratması gibi, hayat da farklılıklarımızın sevgiyle, sabırla ve hoşgörüyle birleştiği anlarda en güzel mucizesini sunar.'",
    "gorsel": "assets/gaziantep.jpg"
  },
  "eskisehir": {
    "baslik": "İçinden Nehir Geçen Masal Şehri",
    "hikaye": "Bir zamanlar, Anadolu'nun ortasında, içinden usulca akan nehrin etrafında kurulmuş, her köşesi sihirli bir masal kitabından fırlamış gibi duran neşeli bir şehir varmış. Bu şehrin adı Eskişehir'miş. Şehrin tam kalbinden süzülen Porsuk Çayı'nın sularında, kırmızı pelerinli gondollar kuğular gibi zarifçe süzülür, köprülerin üzerinden geçen bisikletli çocuklar birbirlerine sevinçle zil çalarlarmış. Dar ve kıvrımlı sokaklara dizilmiş rengarenk ahşap Odunpazarı evleri, birbirine omuz vermiş eski dostlar gibi durur, cumbalı pencerelerinden sokağa sarkan pembe sardunyalar güneşe neşeyle gülümserilmiş.\n\nGüneş gökyüzünde tebessüm ettiğinde, yemyeşil Sazova Parkı'ndaki devasa Masal Şatosu'nun sivri kuleleri pırıl pırıl parlarmış. Bu şatonun etrafında koşturan çocuklar, kocaman göletteki efsanevi korsan gemisinde hazine avına çıkar, asırlık ağaçların gölgesinde pamuk şekerlerini paylaşarak büyülü diyarlara doğru hayallere dalarlarmış. Çarşının ara sokaklarındaki sabırlı ustalar, yeraltından çıkarılan bembeyaz lületaşını ellerinde adeta birer nakış gibi işler, toprağın bu gizli hazinesine sabırla nefes verirlermiş. Şehrin her köşesinde yankılanan kahkahalar, bu güzel şehre hiç bitmeyen bir bahar enerjisi katarmış.\n\nAkşam olup da sokak lambaları Porsuk Çayı'nın sularına altın damlaları gibi yansıdığında, gökyüzü koyu bir laciverte bürünür ve şehir tatlı bir uykuya hazırlanırmış. Gökyüzündeki yıldızlar şatonun kulelerine konarken, nehirden esen ılık rüzgar Odunpazarı evlerinin ahşap saçaklarında ninniler fısıldarmış. Efsaneye göre, bu usulca akan nehrin suları, gece yıldızların altında hayal kurarak uykuya dalan çocukların kulağına şu sırrı fısıldarmış: 'Dünyadaki en güzel masallar kalın kapaklı kitaplarda değil, kalbindeki çocukluk neşesini ve umudunu hiç kaybetmeyenlerin sıcacık gülücümelerinde saklıdır.'",
    "gorsel": "assets/eskisehir.jpg"
  },
  "hatay": {
    "baslik": "Defne Kokulu Hoşgörü Şehri",
    "hikaye": "Bir zamanlar, Akdeniz'in ılık sularının bereketli topraklarla buluştuğu, her sokağında farklı bir masalın fısıldandığı kadim bir şehir varmış. Bu sevgi dolu şehrin adı Hatay'mış. Şehrin tam kalbinden süzülen Asi Nehri, diğer tüm nehirlerin aksine tersine doğru inatla ve gururla akar, etrafındaki tarlalara can verirmiş. Daracık taş sokaklarda neşeyle koşturan çocuklar, yüzlerce yıldır yan yana duran camilerin, kiliselerin ve havraların gölgesinde saklambaç oynar; gökyüzüne yükselen ezan seslerinin çan seslerine karışarak oluşturduğu o muazzam kardeşlik şarkısıyla büyürlermiş.\n\nGüneş en tepeye çıktığında, meşhur Uzun Çarşı'dan yayılan taze zahter, kavrulmuş kahve ve peyniri uzadıkça uzayan sıcacık künefenin kokusu rüzgara karışır, herkesin yüzüne tatlı bir tebessüm kondururmuş. Çocuklar, sabırlı ustaların ellerinden çıkan mozaik taşlarını hayranlıkla izler; binlerce yıl öncesinden kalan bu binbir renkli taşlarda gizlenmiş su perilerinin ve orman kahramanlarının hikayelerine hayallere dalarlarmış. Şehrin etrafını saran yemyeşil dağlarda yeşeren efsanevi defne ağaçları, rüzgar estikçe havaya ferah bir koku yayar ve sokaklarda oynayan çocukların saçlarını şefkatle okşarmış.\n\nAkşam usulca çöküp de güneş Habib-i Neccar Dağı'nın ardında kızıl bir tebessümle kaybolduğunda, taş avlulu evlerin sarı fenerleri teker teker yanarmış. Ortasında küçük bir havuz bulunan serin avlularda nane çayları yudumlanırken, gökyüzündeki yıldızlar çocukların gözlerindeki ışıltıya eşlik edermiş. Efsaneye göre, Asi Nehri'nin serin sularına değerek esen ılık gece rüzgarı, uykuya dalan miniklerin kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en eşsiz lezzet ve en büyük mucize; tıpkı bu şehirdeki gibi, farklı renklerin, seslerin ve kalplerin bir arada, omuz omuza barış içinde atabilmesidir.'",
    "gorsel": "assets/hatay.jpg"
  },
  "cankiri": {
    "baslik": "Kristal Tuzların ve Yarenlerin Şehri",
    "hikaye": "Bir zamanlar, Anadolu'nun sessiz ve bilge köşelerinden birinde, sırtını ulu dağlara yaslamış ve yeryüzünün en gizemli hazinelerini kalbinde saklayan sımsıcak bir şehir varmış. Bu şehrin adı Çankırı'ymış. Şehrin en yüksek tepesindeki asırlık taş kalede rüzgar, eski kahramanların yiğitlik masallarını fısıldar, eteklerindeki dar sokaklarda koşturan çocuklar ise bu masalları neşeyle dinlermiş. Bu güzel şehirde insanlar birbirlerini o kadar çok severmiş ki; dostluğun, saygının ve paylaşmanın en güzel halini 'Yaren' adı verilen o sevgi dolu meclislerde büyüklerinden öğrenir, paylaşılan bir tebessümün dünyadaki en değerli hediye olduğuna inanırlarmış.\n\nBu şehrin yeraltında saklı, parıl parıl parlayan devasa bir sırrı varmış: Hititlerden kalma asırlık Tuz Mağarası. Dev kaya tuzlarının kristalden şatolar gibi parladığı bu yer altı sarayına giren çocuklar, kendilerini büyülü bir masal diyarında zannederlermiş. Kış geldiğinde, hemen yanı başındaki ulu Ilgaz Dağları bembeyaz bir örtüyle kaplanır, çam ağaçlarının dallarından düşen pamuk gibi karlar ormanın sessizliğinde tatlı bir müzik yaparmış. Çocuklar soğuk havaya aldırmadan kızaklarıyla kayarken, havaya karışan soba ve kestane kokusu herkesin içini ısıtırmış.\n\nAkşam karanlığı çöküp de gökyüzü laciverte büründüğünde, ahşap evlerin pencerelerinden süzülen sarı ışıklar taş sokakları aydınlatır, bacalardan tüten ince dumanlar gökyüzündeki yıldızlara usulca selam verirmiş. İçeriden yükselen saz sesleri eşliğinde anlatılan iyilik masalları, karanlığı şefkatle kucaklarmış. Efsaneye göre, yeraltındaki o parlak kristal mağaralardan esip gelen serin rüzgar, yıldızların altında uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Yeryüzündeki en tükenmez ve en parlak hazine yerin altında saklı olanlar değil; dostlukla, vefayla ve sevgiyle birbirine sımsıkı bağlanan altın kalplerdir.'",
    "gorsel": "assets/cankiri.jpg"
  },
  "kastamonu": {
    "baslik": "Zümrüt Ormanların ve Cesur Yüreklerin Şehri",
    "hikaye": "Bir zamanlar, Karadeniz'in serin sularına tepeden bakan, dört bir yanı zümrüt yeşili ulu ormanlarla çevrili, havası mis gibi çam kokan görkemli bir şehir varmış. Bu kahraman yürekli şehrin adı Kastamonu'ymış. Şehrin tam kalbinde, tepeden tüm şehri izleyen asırlık Saat Kulesi, her saat başı gür sesiyle gökyüzündeki beyaz bulutlara ve uçuşan güvercinlere neşeyle selam verirmiş. Daracık taş sokaklara dizilmiş, ahşap oymalı zarif konakların gölgesinde koşturan çocuklar, Nasrullah Camii'nin tarihi şadırvanından su içip serinlerken, atalarının o dilden dile dolaşan cesaret masallarıyla büyürlermiş.\n\nGüneş tepeye tırmandığında, Küre Dağları'nın gizemli kanyonlarında ve derin vadilerinde saklanan doğa perileri uyanır, gürül gürül akan şelaleler ormanın derinliklerine taptaze bir hayat verirmiş. İlkbaharda doğa uykusundan uyandığında, Taşköprü'nün bereketli topraklarından neşe fışkırır, yemyeşil yaylalara koşan çocuklar rengarenk kır çiçeklerinden kendilerine taçlar yaparlarmış. Kış gelip de ulu Ilgaz Dağları bembeyaz, pamuktan bir örtüyle kaplandığında, yanakları soğuktan al al olmuş çocuklar kızaklarıyla karların üzerinde rüzgarla yarışırdı. Bu şehrin minikleri, efsanevi Şerife Bacı'nın torunları oldukları için minicik kalplerinde daima devasa bir cesaret, iyilik ve tükenmez bir umut taşırmış.\n\nAkşam karanlığı usulca çöktüğünde, ahşap konakların kafesli pencerelerinden süzülen sıcacık sarı ışıklar taş sokakları aydınlatır, kuzinelerin üzerinde demlenen çayların kokusu herkesin içini ısıtırmış. Karadeniz'in kıyısından ve ulu ormanların derinliklerinden kopup gelen gece rüzgarı, gökyüzündeki parıl parıl yıldızlara usulca dokunup şehri şefkatle kucaklarmış. Efsaneye göre, asırlık çam ağaçlarının tatlı hışırtısı, soba başında masal dinleyerek uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en sarsılmaz kale taştan ve topraktan yapılanlar değil; doğasına, yurduna ve sevdiklerine hiçbir karşılık beklemeden, cesaretle ve sımsıkı sarılan o kocaman yüreklerdir.'",
    "gorsel": "assets/kastamonu.jpg"
  },
  "kahramanmaras": {
    "baslik": "Ahir Dağı'nın Cesur ve Tatlı Masalı",
    "hikaye": "Bir zamanlar, ulu Ahir Dağı'nın serin eteklerine şefkatle yaslanmış, havasında hem dağların ferahlığını hem de eşsiz bir cesaret taşıyan görkemli bir şehir varmış. Bu kahraman yürekli şehrin adı Maraş'mış. Tarihi taş konakların sıralandığı, ceviz ağaçlarının gölgelediği kıvrımlı sokaklarda neşeyle koşturan çocuklar, atalarının anlattığı o destansı kahramanlık masallarıyla büyür, minicik kalplerinde dünyaya meydan okuyacak kocaman bir cesaret taşırlarmış.\n\nGüneş sokakları ısıttığında, tarihi Kapalı Çarşı'dan yükselen bakırcıların ritmik çekiç seslerine, dondurma ustalarının o neşeli 'çat çat' sesleri eşlik edermiş. Ahir Dağı'nın yaban orkidelerinden gelen sihirli saleple keçi sütünü buluşturan sabırlı ustalar, bembeyaz dondurmayı metrelerce gökyüzüne uzatarak çocuklara tatlı bir sihirbazlık gösterisi yaparmış. Külahını kapmaya çalışan çocukların şen kahkahaları havaya karışırken, yaz aylarında bembeyaz örtülere serilip kurutulan meşhur tarhanalar tüm şehre bereketli ve huzur veren bir koku yayarmış.\n\nAkşam karanlığı usulca çöküp de gökyüzü koyu bir laciverte büründüğünde, şehre yukarıdan bakan asırlık kalenin burçlarında yanan sarı ışıklar karanlığı şefkatle aydınlatırmış. Geniş taş avlularda toplanan aileler, gökyüzündeki pırıl pırıl yıldızların altında sevgiyle sohbet ederken şehir tatlı bir uykuya hazırlanırmış. Efsaneye göre, Ahir Dağı'nın zirvesinden kopup gelen serin gece rüzgarı, uykuya dalan cesur yürekli çocukların kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en tatlı ve en unutulmaz mucize; zorluklar karşısında asla pes etmeyen kahraman bir yürekle, sevdiklerine umut dolu bir tebessüm sunabilmektir.'",
    "gorsel": "assets/kahramanmaras.jpg"
  },
  "rize": {
    "baslik": "Bulutlara Tutunan Zümrüt Şehir",
    "hikaye": "Bir zamanlar, gökyüzünün yeryüzüne aşık olduğu ve sevgi gözyaşlarının dağları zümrüt yeşili bir halıya çevirdiği, bulutlara komşu bir şehir varmış. Bu yağmur kokulu şehrin adı Rize'ymiş. Şehrin etrafını saran heybetli Kaçkar Dağları, zirvelerindeki beyaz karları gökyüzünün pamuk bulutlarına karıştırırken, yamaçlarında koşturan çocuklar adeta bulutların üzerinde seksek oynarmış. Dik yamaçlardaki tarihi taş köprülerden neşeyle geçen ve Fırtına Deresi'nin coşkulu sesiyle büyüyen bu minikler, doğanın o deli dolu ama şefkatli kalbini çok iyi bilirlermiş.\n\nGüneş bulutların arasından gülümsediğinde, uçsuz bucaksız çay tarlalarında hasat başlar, yeşil yaprakların arasına karışan neşeli türkülere tulumun o kıpır kıpır sesi eşlik edermiş. Yanakları yayla havasından al al olmuş insanlar sepetlerini yemyeşil umutlarla doldururken, ahşap serenderlerin gölgesinde saklambaç oynayan çocuklar yağmur damlalarının yapraklar üzerindeki parıltısını hayranlıkla izlermiş. Sislerin arasından süzülerek beliren ulu çam ormanları ve gürül gürül akan şelaleler, bu topraklara hiç bitmeyen bir enerji ve derin bir huzur katarmış.\n\nAkşam usulca çöküp de hırçın Karadeniz sakinleştiğinde, ahşap yayla evlerinin sobalarında yanan odunların çıtırtısı duyulur, havaya taze demlenmiş mis gibi çay kokusu yayılırmış. Gökyüzü laciverte büründüğünde, dağların zirvesindeki parlak yıldızlar çocukların pencerelerine konarak onlara masallar fısıldarmış. Efsaneye göre, vadilerin derinliklerinden süzülüp gelen serin yayla rüzgarı, uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en güçlü güzellik, tıpkı bu zümrüt dağlar gibi; hem zorlu yağmurlarla hem de neşeli güneşle beslenip hayata sevgiyle, inatla tutunmaktır.'",
    "gorsel": "assets/rize.jpg"
  },
  "sivas": {
    "baslik": "Selçuklu'nun Taşlara Kazınmış Masalı",
    "hikaye": "Bir zamanlar, Anadolu'nun uçsuz bucaksız sarı bozkırlarının tam ortasında, soğuk kışlarına inat insanlarının kalbinde sıcacık bir ateş yanan kadim bir şehir varmış. Bu bilgelik dolu şehrin adı Sivas'mış. Şehrin meydanında, gökyüzüne doğru gururla uzanan Çifte Minareli Medrese ve masmavi çinileriyle güneş gibi parlayan Gök Medrese bulunurmuş. Kapılarındaki heybetli çift başlı kartal figürlerinin gölgesinde seksek oynayan çocuklar, taş ustalarının yüzyıllar önce ilmek ilmek işlediği bu büyüleyici masalın içinde neşeyle koştururlarmış.\n\nGüneş en tepeye tırmandığında, altın sarısı buğday tarlalarının rüzgarda usulca dalgalandığı köylerde, devasa boyları ama altın gibi kalpleriyle meşhur Sivas Kangal köpekleri, sürülere ve oyun oynayan çocuklara şefkatle yoldaşlık edermiş. Uzak dağların ardındaki Divriği'de ise, usta ellerin taşa nakşettiği o ulu caminin kapısına ikindi güneşi vurduğunda, gölgelerden okunan sihirli bir silüet belirir ve bu mucizeyi izleyen çocukların gözleri hayranlıkla parlarmış. Bozkırın sessizliğinde, bir ozanın elindeki sazın tellerinden dökülen türküler Kızılırmak'ın usulca akan sularına karışarak tüm topraklara barış ve dostluk eker, bahar geldiğinde yamaçlarda açan çiçekler bu türkülere neşeyle eşlik edermiş.\n\nAkşam karanlığı usulca çöküp de Kızılırmak gecenin koynunda gümüş gibi parladığında, ahşap konakların pencerelerinden süzülen sıcacık sarı ışıklar taş sokakları aydınlatırmış. Gökyüzü koyu bir laciverte bürünürken, bozkırın üzerindeki parlak yıldızlar adeta yeryüzüne inip çocuklara masallar anlatmak istermiş. Efsaneye göre, tarihi medreselerin taç kapılarından süzülen serin gece rüzgarı, saz sesleri eşliğinde uykuya dalan miniklerin kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en kalıcı eserler sert taşlara kazınanlar değil; dostluğa, sadakate ve sevgiyle söylenen bir türkünün tellerine sonsuza dek işlenenlerdir.'",
    "gorsel": "assets/sivas.jpg"
  },
  "kayseri": {
    "baslik": "Erciyes'in Karlı Zirvesindeki Lezzet Şehri",
    "hikaye": "Bir zamanlar, başı gökyüzündeki bulutlara değen, yaz kış üzerinden beyaz pelerinini hiç çıkarmayan ulu Erciyes Dağı'nın eteklerinde, çalışkan ve güler yüzlü insanların yaşadığı kadim bir şehir varmış. Bu şehrin adı Kayseri'ymiş. Şehrin tam kalbinde siyah bazalt taşlardan yapılmış, asırlara meydan okuyan görkemli bir kale dururmuş. Bu tarihi kalenin burçlarında uçuşan güvercinlere neşeyle selam veren çocuklar, eski taş sokaklarda seksek oynar, dağın serin ve ferahlatıcı rüzgarıyla nefes alırlarmış.\n\nGüneş gökyüzünde tebessüm edip de çarşının kepenkleri açıldığında, tarihi Kapalı Çarşı'dan yükselen o neşeli ve telaşlı sesler tüm şehre yayılırmış. Maharetli annelerin özenle hazırladığı, bir tahta kaşığa kırk tanesinin sığdığı o meşhur mantıların mis gibi kokusu, havaya karışan çemen ve taze baharat kokularıyla buluşur, dar sokaklarda koşturan miniklerin içini ısıtırmış. Çalışkan zanaatkarların tezgâhlarından yükselen ritmik tıkırtılar, şehrin hiç bitmeyen o bereketli enerjisine şarkı gibi eşlik ederken; çocuklar alın terinin ve el emeğinin ne kadar kıymetli olduğunu bu çarşının taş duvarları arasında öğrenirlermiş.\n\nAkşam usulca çöküp de güneş Erciyes'in ardında gülümsediğinde, dağın zirvesindeki beyaz karlar ay ışığında gümüş bir taç gibi parlamaya başlarmış. Taş avlulu evlerin pencerelerinden sızan sıcacık sarı ışıklar, kurulan büyük sofraların neşesini sessizleşen sokaklara taşırmış. Efsaneye göre, Erciyes'in zirvesinden süzülüp gelen serin gece rüzgarı, yıldızların altında masal dinleyerek uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en büyük zenginlik altın, gümüş veya ticarette değil; sabırla, emekle ve sevgiyle yoğrulan sıcacık bir lokmayı sevdiklerinle paylaşabilmektedir.'",
    "gorsel": "assets/kayseri.jpg"
  },
  "afyonkarahisar": {
    "baslik": "Göğe Uzanan Siyah Taşın Tatlı Masalı",
    "hikaye": "Bir zamanlar, Anadolu'nun yollarının kesiştiği, etrafı ulu dağlarla çevrili ve tam ortasında gökyüzüne doğru devasa siyah bir kayanın yükseldiği masalsı bir şehir varmış. Bu efsanevi şehrin adı Afyonkarahisar'mış. Bulutları delip geçen bu sarp kayanın tam zirvesinde, eski zamanlardan kalma Karahisar Kalesi, eteklerine kurulan eski ahşap konaklara ve dar sokaklara şefkatle bekçilik edermiş. Kalenin yüzlerce basamaklı merdivenlerinde neşeyle seksek oynayan çocuklar, volkanik kayaların gizemli hikayeleriyle büyür, yeraltından kaynayarak yeryüzüne çıkan şifalı sıcak suların bu topraklara iyilik perileri tarafından armağan edildiğine inanırlarmış.\n\nGüneş doğup da şehri ısıttığında, fırınlardan yükselen sıcacık haşhaşlı çöreklerin ve taze kaymağın o baş döndürücü kokusu tüm sokakları sararmış. Maharetli ustaların sabırla hazırladığı lokumlar çocukların yüzünde eşsiz bir tebessüm yaratırken, bembeyaz mermer atölyelerinden gelen çekiç sesleri şehrin hiç bitmeyen şarkısına ritim tutarmış. İlkbahar gelip de ovalar uykusundan uyandığında, uçsuz bucaksız tarlalar mor ve beyaz haşhaş çiçekleriyle bezenir, bu masalsı çiçek denizi rüzgarda dalgalandıkça, gizemli Frig Vadisi'nin asırlık peribacalarına neşeli türküler taşırmış.\n\nAkşam karanlığı usulca çöktüğünde ve ulu Karahisar Kalesi altın rengi ışıklarla aydınlatıldığında, bu devasa kaya adeta gökyüzünde asılı duran sihirli bir taca dönüşürmüş. Tarihi evlerin cumbalı pencerelerinden süzülen ışıklar taş sokakları aydınlatırken, şifalı kaplıcaların huzur veren buğusu yıldızlı geceye usulca karışırmış. Efsaneye göre, Frigya'nın kadim vadilerinden esip gelen serin gece rüzgarı, uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en eşsiz mucize; en sarp ve sert kayaların ardında sımsıcak bir şifa, en zorlu günlerin içinde ise sevdiklerinle paylaştığın lokum tadında bir umut saklı olmasıdır.'",
    "gorsel": "assets/afyonkarahisar.jpg"
  },
  "bursa": {
    "baslik": "Uludağ'ın Zümrüt Yeşili ve İpek Masalı",
    "hikaye": "Bir zamanlar, heybetli Uludağ'ın eteklerine sevgiyle sarılmış, her köşesinden yeşilin binbir tonu fışkıran masalsı bir şehir varmış. Bu bereketli şehrin adı Bursa'ymış. Gökyüzüne doğru kırmızı kabinleriyle süzülen teleferiklere binen çocuklar, adeta pamuk bulutların arasında uçar, ulu çınarların gölgelediği taş sokaklarda neşeyle seksek oynarlarmış. Şehrin kalbinde duran görkemli Ulu Cami'nin içindeki şadırvandan usulca akan su sesi, etrafında toplanan çocuklara eski zaman bilgelerinin huzur dolu masallarını anlatırmış.\n\nGüneş tepeye tırmandığında, tarihi Koza Han'ın taş avlusundan taze demlenmiş çay ve kavrulmuş kestane şekeri kokusu yükselir, tüm şehrin içini tatlı bir sevinçle doldururmuş. Sabırlı ipekböceklerinin incecik ipliklerle ördüğü altın sarısı kozalar, usta ellerde yeryüzünün en zarif ve yumuşacık ipek kumaşlarına dönüşürmüş. İlkbahar gelip de tabiat uykusundan uyandığında, Cumalıkızık'ın rengarenk ahşap evlerinin arasından akan serin sular, taş parke yollardan seke seke aşağıya inerek çocukların şen kahkahalarına eşlik edermiş.\n\nAkşam karanlığı çöküp de Uludağ'ın serinliği şehre doğru usulca indiğinde, ovanın üzerini kaplayan sarı ışıklar Bursa'yı yıldızlardan örülmüş bir battaniye gibi sararmış. Asırlık çınar ağaçlarının yaprakları gece rüzgarında tatlı tatlı hışırdarken, şehir huzurlu bir uykuya hazırlanırmış. Efsaneye göre, dağın karlı zirvesinden esip gelen serin gece rüzgarı, ipek gibi yumuşak bir uykuya dalan çocukların kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en değerli kumaş ipekten dokunanlar değil; doğaya, geçmişine ve birbirine sevgiyle, saygıyla sımsıkı bağlanan yeşil kalplerdir.'",
    "gorsel": "assets/bursa.jpg"
  },
  "adana": {
    "baslik": "Seyhan'ın Portakal Çiçeği Kokulu Masalı",
    "hikaye": "Bir zamanlar, uçsuz bucaksız ve bereketli Çukurova'nın kalbinde, güneşin yılın her mevsimi gülümsediği sımsıcak bir şehir varmış. Bu altın kalpli şehrin adı Adana'ymış. Şehrin tam ortasından nazlı nazlı akan Seyhan Nehri, sularında gökyüzünün mavisini taşırken; nehrin üzerindeki asırlık Taşköprü, binlerce yıllık sırları sessizce göğsünde saklarmış. Bu kadim köprünün taşlarında neşeyle koşturan çocuklar, nehirdeki gümüş renkli balıkları izler ve suyun anlattığı eski zaman masallarıyla büyürlermiş.\n\nİlkbahar geldiğinde bu şehre adeta sihirli bir değnek dokunur, her sokağı baş döndürücü bir portakal çiçeği kokusu sararmış. Ağaçlar bembeyaz gelinliklerini giydiğinde çocuklar sokağa dökülür, neşeli karnavallarda baharın gelişini coşkuyla kutlarlarmış. Güneş tepeye tırmandığında ise, uçsuz bucaksız tarlalarda rüzgarla dalgalanan pamuklar, tıpkı yeryüzüne inmiş bulut tarlaları gibi bembeyaz parlarmış. Tarihi Kazancılar Çarşısı'ndan yükselen ritmik bakır çekiç seslerine, şalgamcıların neşeli çağrıları ve ocaklardan yükselen iştah açıcı baharat kokuları karışır, şehrin o bitmek bilmeyen enerjisi herkesin içini ısıtırmış.\n\nAkşam usulca çöküp de güneş Çukurova'nın ardında kızıl bir ateş gibi kaybolduğunda, nehir kenarındaki parklar cıvıl cıvıl insanlarla dolar, şehir serinleyen havayla birlikte derin bir nefes alırmış. Seyhan Nehri'nin suları köprülerin sarı ışıklarını bir ayna gibi yansıtırken, Adana huzurlu bir uykuya hazırlanırdı. Efsaneye göre, bereketli tarlalardan süzülüp gelen ılık güney rüzgarı, yıldızların altında hayal kuran miniklerin kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en büyük bereket toprağın beyaz altınında değil; tıpkı bu şehrin güneşi gibi etrafını kavrayan, cömert ve sımsıcak kalplerdedir.'",
    "gorsel": "assets/adana.jpg"
  },
  "van": {
    "baslik": "Masmavi Denizin ve Büyülü Kedilerin Şehri",
    "hikaye": "Bir zamanlar, karlı ulu dağların kucağında, masmavi ve uçsuz bucaksız sularıyla adeta gizli bir deniz gibi parlayan kocaman bir gölün kıyısına kurulmuş büyülü bir şehir varmış. Bu kadim şehrin adı Van'mış. Şehrin tam kalbinde, tarihin sırlarını fısıldayan heybetli Van Kalesi, eteklerindeki bereketli topraklara şefkatle nöbet tutarmış. Bu masalsı sokaklarda, bir gözü gökyüzü gibi masmavi, diğer gözü güneş gibi sapsarı olan pamuk tüylü efsanevi Van kedileri usulca dolaşır, çocuklarla saklambaç oynayıp onlara masmavi gölün eski sırlarını anlatırmış.\n\nGüneş dağların ardından altın bir tepsi gibi doğduğunda, mis gibi kokan taptaze otlu peynirlerin ve sıcacık pidelerin süslediği o dünyaca meşhur kocaman kahvaltı sofraları kurulur, dostluklar ve neşe bu bereketli sofralarda çoğalırmış. İlkbahar gelip de karlar eridiğinde, suların ortasındaki Akdamar Adası pembe ve beyaz badem çiçekleriyle donanır, adeta suyun üzerinde yüzen bir masal tacına dönüşürmüş. Göç vakti geldiğinde ise, akıntının tersine, gökyüzüne doğru inatla zıplayarak yüzen cesur inci kefali balıkları, nehir kenarında onları hayranlıkla izleyen çocuklara pes etmemenin ve azmin en muazzam dansını sergilermiş.\n\nAkşam usulca çöküp de güneş Van Gölü'nün sularında kızıl ve mor renklere bürünerek usulca battığında, durgun göl gökyüzündeki binlerce yıldıza devasa bir ayna olurmuş. Taş evlerin pencerelerinden süzülen sarı ışıklar, gölün yakamozlarına karışarak şehri tatlı bir uykuya hazırlarmış. Efsaneye göre, bu efsunlu gölün serin sularından esip gelen gece rüzgarı, yıldızların altında hayal kurarak uykuya dalan miniklerin kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en eşsiz güzellik, tıpkı o sihirli kedilerin iki farklı renkteki gözü gibi, farklılıkların sevgiyle bir araya gelerek oluşturduğu kusursuz uyumda saklıdır.'",
    "gorsel": "assets/van.jpg"
  },
  "diyarbakir": {
    "baslik": "Kara Surların ve Hevsel'in Kadim Masalı",
    "hikaye": "Bir zamanlar, uçsuz bucaksız Mezopotamya ovasını şefkatle kucaklayan, simsiyah bazalt taşlardan örülmüş efsanevi surların ardında, kalbi sımsıcak atan kadim bir şehir varmış. Bu dayanıklı ve yiğit şehrin adı Diyarbakır'mış. Gökyüzünden bakıldığında devasa bir kalkan balığını andıran bu ulu surların dört bir yanındaki heybetli kapılardan süzülen rüzgar, eski zaman masallarını sokaklara taşırmış. Dört Ayaklı Minare'ye çıkan daracık taş sokaklarda neşeyle koşturan çocuklar, gölgeli avlularından su sesleri eksik olmayan eski taş evlerde omuz omuza, sevgiyle büyürlermiş.\n\nGüneş tepeye tırmandığında, şehrin hemen yanı başında nazlı nazlı akan Dicle Nehri, efsanevi Hevsel Bahçeleri'ne can verir, doğanın en güzel zümrüt yeşillerini bu bereketli topraklara armağan edermiş. Yazın o kavurucu sıcağında, neredeyse bir çocuk kadar büyük olan meşhur kırmızı karpuzlar çatlatılır, paylaşılan o serin neşe tüm miniklerin yüzünü güldürürmüş. Bakırcılar Çarşısı'ndan yükselen ritmik çekiç sesleri ile gökyüzüne doğru süzülen taklacı güvercinlerin kanat çırpışları birbirine karışır, asırlık Hasan Paşa Hanı'nda yudumlanan sıcacık kahvelerin etrafında bitmek bilmeyen dostluk ve kardeşlik hikayeleri anlatılırmış. On Gözlü Köprü'nün taş kemerleri üzerinden geçen rüzgar, nehrin o tatlı ninnisini uzak diyarlara kadar taşırmış.\n\nAkşam karanlığı çöküp de gökyüzü koyu bir laciverte büründüğünde, kara surların üzerine vuran ay ışığı şehre gümüşten ve pırıltılı bir zırh giydirirmiş. Avlulardaki ahşap tahtların üzerine kurulan yer yataklarında gökyüzünü izleyen çocuklar, parlayan yıldızların aslında Mezopotamya'nın iyilik perileri olduğuna inanırmış. Efsaneye göre, Dicle Nehri'nin serin sularından süzülüp gelen ılık gece rüzgarı, yıldızların altında uykuya dalan miniklerin kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en sarsılmaz surlar sert kayalardan örülenler değil; sevgiyle, hoşgörüyle ve kardeşlikle birbirine sımsıkı kenetlenen o kocaman yüreklerdir.'",
    "gorsel": "assets/diyarbakir.jpg"
  },
  "mersin": {
    "baslik": "Limon Kokulu Denizin Masal Şehri",
    "hikaye": "Bir zamanlar, ulu Toros Dağları'nın Akdeniz'in ılık sularıyla kucaklaştığı, havası her daim taze limon ve portakal çiçeği kokan sımsıcak bir şehir varmış. Bu bereketli şehrin adı Mersin'miş. Şehrin kıyısından biraz uzakta, denizin tam ortasında suların üzerinde zarifçe süzülen gizemli bir taş şato dururmuş; adına Kızkalesi derlermiş. Altın sarısı kumsallarda neşeyle koşturan çocuklar, dalgaların kıyıya vuran tatlı ritmiyle seksek oynar, suların ortasındaki bu masalsı kalenin içinde eski zamanlardan kalma iyilik perilerinin yaşadığına inanırlarmış.\n\nGüneş gökyüzünde tebessüm ettiğinde, Tarsus'un gürül gürül akan şelaleleri etrafa serin damlalar saçar, yazın o tatlı sıcağında gölgede dinlenen çocuklara ferah bir doğa şarkısı söylermiş. Uçsuz bucaksız narenciye bahçelerinde açan bembeyaz çiçekler rüzgarla dans ederken, sokaklardan yükselen mis gibi havuçlu cezerye kokusu herkesin yüzüne kocaman bir gülümseme kondururmuş. Yemyeşil vadilerin derinliklerinde gizlenen Cennet ve Cehennem obruklarının asırlık sessizliği, rüzgar estikçe eski çağ kahramanlarının maceralarını fısıldar, bu kadim topraklardaki miniklerin hayal gücünü gökyüzünün en uçsuz köşelerine taşırmış.\n\nAkşam karanlığı usulca çöküp de güneş Akdeniz'in ufkunda kızıl bir ateş gibi eridiğinde, denizin ortasındaki Kızkalesi'nin altın rengi ışıkları yanar ve sulara büyülü bir yakamoz bırakırmış. Sahil boyunca uzanan ulu palmiye ağaçları gece rüzgarıyla usulca sallanırken, ufuktaki gemilerin fenerleri yıldızlara karışarak şehri tatlı bir uykuya hazırlarmış. Efsaneye göre, Akdeniz'in ılık sularından süzülüp gelen gece meltemi, dalga sesleri eşliğinde uykuya dalan miniklerin kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en sarsılmaz güzellik; tıpkı denizin ortasında inatla ve zarafetle duran o taş kale gibi, hayatın dalgalarına sevgiyle, cesaretle ve umutla göğüs gerebilmektir.'",
    "gorsel": "assets/mersin.jpg"
  },
  "kocaeli": {
    "baslik": "Mavi Körfezin ve Tel Tel Dağılan Tatlı Bulutların Şehri",
    "hikaye": "Bir zamanlar, yemyeşil tepelerin kollarını açıp masmavi bir denizi şefkatle kucakladığı, rüzgarın deniz tuzu ve çam kokusunu birbirine karıştırdığı çalışkan bir şehir varmış. Bu üretken ve güzel şehrin adı Kocaeli'ymiş. Şehrin tepesinde, zarafetle gökyüzüne uzanan tarihi İzmit Saat Kulesi, körfezin sularında süzülen gemilere ve sahilde uçurtma uçuran çocuklara neşeyle zamanı fısıldarmış. Sekapark'ın uçsuz bucaksız çimenliklerinde koşturan çocuklar, kanat çırpan martıların şarkılarına eşlik eder, denizin o huzur veren tatlı maviliğiyle büyürlermiş.\n\nGüneş tepeye tırmandığında, şehrin sihirli atölyelerinden dünyanın en hafif ve en tatlı lezzetinin kokusu yayılırmış: Pişmaniye. Sabırlı ustaların ellerinde pamuk gibi tel tel uzayan, tıpkı gökyüzünden yeryüzüne inmiş tatlı bembeyaz bulutlara benzeyen bu efsanevi şekerleme, çocukların yüzünde kocaman gülücükler açtırırmış. Bir yanda devasa çarkların ve makinelerin durmaksızın çalıştığı devasa atölyeler ateş böcekleri gibi ışıl ışıl parlarken, diğer yanda ulu Kartepe'nin zirvesi kışın bembeyaz kardan bir şapka takar, ilkbaharda ise orman perilerinin saklandığı zümrüt yeşili bir masala dönüşürmüş. Bu şehrin insanları hem demiri ve ateşi sevgiyle işler hem de doğanın kalbine sımsıkı sarılırmış.\n\nAkşam usulca çöküp de güneş İzmit Körfezi'nin sularına altın rengi bir veda busesi kondurduğunda, karşı kıyılardaki binlerce lamba usulca yanar ve körfez devasa, ışıltılı bir gerdanlığa dönüşürmüş. Limana yanaşan dev gemilerin tatlı siren sesleri, dalgaların ninnisine karışarak şehri huzurlu bir uykuya hazırlarmış. Efsaneye göre, körfezin serin sularından süzülüp gelen gece meltemi, yıldızların altında uykuya dalan miniklerin kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en büyük başarı, tıpkı o tatlı bulutlar gibi sabırla ve emekle yoğrulmak; en yoğun günlerin içinde bile kalbindeki o dingin maviliği ve sevgiyi asla kaybetmemektir.'",
    "gorsel": "assets/kocaeli.jpg"
  },
  "adiyaman": {
    "baslik": "Güneşin Dev Heykellerle Dans Ettiği Masal Şehri",
    "hikaye": "Bir zamanlar, Fırat Nehri'nin bereketli sularıyla kucaklaştığı, dağların zirvesinde sırlarla dolu dev heykellerin gökyüzünü izlediği efsunlu bir şehir varmış. Bu gizemli şehrin adı Adıyaman'mış. Şehrin kalbinde yükselen ulu Nemrut Dağı'nın zirvesinde, binlerce yıl öncesinden kalma taştan dev krallar, aslanlar ve koruyucu kartallar usulca oturur, yeryüzüne şefkatle bakarlarmış. Bu masalsı topraklarda büyüyen çocuklar, usta ellerden çıkma bu devasa yüzlerin aslında eski zamanların iyilik melekleri olduğuna inanır, rüzgarın taşıdığı Kommagene masallarıyla koştururlarmış.\n\nGüneş, yeryüzünde en güzel bu ulu dağın zirvesinden doğarmış. Şafak vakti gökyüzü turuncu, kızıl ve altın sarısı renklere boyandığında, taş heykellerin yüzüne vuran ilk ışıklar adeta tüm şehre neşeli bir günaydın dermiş. Dağın eteklerindeki uçsuz bucaksız tarlalarda salkım salkım üzümler ve taptaze narlar güneşle tatlanır, çalışkan ve güler yüzlü insanlar bu bereketi sevgiyle paylaşırmış. Tarihi Cendere Köprüsü'nün sağlam taş kemerleri altından akan serin sular, sokaklarda oynayan çocukların şen kahkahalarına karışarak Fırat Nehri'nin o görkemli ve sakin kollarına doğru huzurla süzülürmüş.\n\nAkşam usulca çöküp de güneş Nemrut Dağı'nın ardında kızıl bir ateş gibi eridiğinde, gökyüzü mor ve lacivert bir pelerin giyermiş. Dev heykellerin arasından esen gece rüzgarı taşların üzerinde masallar mırıldanırken, toprak damlı evlerin avlularında yıldızları izleyen çocuklar için gökyüzü devasa bir masala dönüşürmüş. Efsaneye göre, Fırat'ın serin sularından süzülüp dev heykellerin asırlık yüzlerini okşayan o ılık gece rüzgarı, uykuya dalan miniklerin kulağına şu kadim sırrı fısıldarmış: 'Dünyadaki en kalıcı güç, yüksek dağlara taştan heykeller dikmek değil; tıpkı bu zirvedeki gibi, doğan ve batan her güneşi kalbinde sevgi, kardeşlik ve tükenmez bir umutla kucaklayabilmektir.'",
    "gorsel": "assets/adiyaman.jpg"
  },
};